use evdev::KeyCode;

#[inline]
pub fn keycode_to_ru_char(keycode: u16, shift: bool) -> Option<char> {
    use KeyCode as K;
    let key = KeyCode::new(keycode);
    if shift {
        return match key {
            K::KEY_Q => Some('Й'),
            K::KEY_W => Some('Ц'),
            K::KEY_E => Some('У'),
            K::KEY_R => Some('К'),
            K::KEY_T => Some('Е'),
            K::KEY_Y => Some('Н'),
            K::KEY_U => Some('Г'),
            K::KEY_I => Some('Ш'),
            K::KEY_O => Some('Щ'),
            K::KEY_P => Some('З'),
            K::KEY_LEFTBRACE => Some('Х'),
            K::KEY_RIGHTBRACE => Some('Ъ'),
            K::KEY_A => Some('Ф'),
            K::KEY_S => Some('Ы'),
            K::KEY_D => Some('В'),
            K::KEY_F => Some('А'),
            K::KEY_G => Some('П'),
            K::KEY_H => Some('Р'),
            K::KEY_J => Some('О'),
            K::KEY_K => Some('Л'),
            K::KEY_L => Some('Д'),
            K::KEY_SEMICOLON => Some('Ж'),
            K::KEY_APOSTROPHE => Some('Э'),
            K::KEY_Z => Some('Я'),
            K::KEY_X => Some('Ч'),
            K::KEY_C => Some('С'),
            K::KEY_V => Some('М'),
            K::KEY_B => Some('И'),
            K::KEY_N => Some('Т'),
            K::KEY_M => Some('Ь'),
            K::KEY_COMMA => Some('Б'),
            K::KEY_DOT => Some('Ю'),
            K::KEY_GRAVE => Some('Ё'),
            K::KEY_1 => Some('!'),
            K::KEY_2 => Some('"'),
            K::KEY_3 => Some('№'),
            K::KEY_4 => Some(';'),
            K::KEY_5 => Some('%'),
            K::KEY_6 => Some(':'),
            K::KEY_7 => Some('?'),
            K::KEY_8 => Some('*'),
            K::KEY_9 => Some('('),
            K::KEY_0 => Some(')'),
            K::KEY_MINUS => Some('_'),
            K::KEY_EQUAL => Some('+'),
            K::KEY_SLASH => Some(','),
            K::KEY_SPACE => Some(' '),
            _ => None,
        };
    }

    match key {
        K::KEY_Q => Some('й'),
        K::KEY_W => Some('ц'),
        K::KEY_E => Some('у'),
        K::KEY_R => Some('к'),
        K::KEY_T => Some('е'),
        K::KEY_Y => Some('н'),
        K::KEY_U => Some('г'),
        K::KEY_I => Some('ш'),
        K::KEY_O => Some('щ'),
        K::KEY_P => Some('з'),
        K::KEY_LEFTBRACE => Some('х'),
        K::KEY_RIGHTBRACE => Some('ъ'),
        K::KEY_A => Some('ф'),
        K::KEY_S => Some('ы'),
        K::KEY_D => Some('в'),
        K::KEY_F => Some('а'),
        K::KEY_G => Some('п'),
        K::KEY_H => Some('р'),
        K::KEY_J => Some('о'),
        K::KEY_K => Some('л'),
        K::KEY_L => Some('д'),
        K::KEY_SEMICOLON => Some('ж'),
        K::KEY_APOSTROPHE => Some('э'),
        K::KEY_Z => Some('я'),
        K::KEY_X => Some('ч'),
        K::KEY_C => Some('с'),
        K::KEY_V => Some('м'),
        K::KEY_B => Some('и'),
        K::KEY_N => Some('т'),
        K::KEY_M => Some('ь'),
        K::KEY_COMMA => Some('б'),
        K::KEY_DOT => Some('ю'),
        K::KEY_GRAVE => Some('ё'),
        K::KEY_SLASH => Some('.'),
        K::KEY_1 => Some('1'),
        K::KEY_2 => Some('2'),
        K::KEY_3 => Some('3'),
        K::KEY_4 => Some('4'),
        K::KEY_5 => Some('5'),
        K::KEY_6 => Some('6'),
        K::KEY_7 => Some('7'),
        K::KEY_8 => Some('8'),
        K::KEY_9 => Some('9'),
        K::KEY_0 => Some('0'),
        K::KEY_MINUS => Some('-'),
        K::KEY_EQUAL => Some('='),
        K::KEY_SPACE => Some(' '),
        _ => None,
    }
}
