use evdev::KeyCode;

#[inline]
pub fn keycode_to_us_char(keycode: u16, shift: bool) -> Option<char> {
    use KeyCode as K;
    let key = KeyCode::new(keycode);
    if shift {
        return match key {
            K::KEY_A => Some('A'),
            K::KEY_B => Some('B'),
            K::KEY_C => Some('C'),
            K::KEY_D => Some('D'),
            K::KEY_E => Some('E'),
            K::KEY_F => Some('F'),
            K::KEY_G => Some('G'),
            K::KEY_H => Some('H'),
            K::KEY_I => Some('I'),
            K::KEY_J => Some('J'),
            K::KEY_K => Some('K'),
            K::KEY_L => Some('L'),
            K::KEY_M => Some('M'),
            K::KEY_N => Some('N'),
            K::KEY_O => Some('O'),
            K::KEY_P => Some('P'),
            K::KEY_Q => Some('Q'),
            K::KEY_R => Some('R'),
            K::KEY_S => Some('S'),
            K::KEY_T => Some('T'),
            K::KEY_U => Some('U'),
            K::KEY_V => Some('V'),
            K::KEY_W => Some('W'),
            K::KEY_X => Some('X'),
            K::KEY_Y => Some('Y'),
            K::KEY_Z => Some('Z'),
            K::KEY_1 => Some('!'),
            K::KEY_2 => Some('@'),
            K::KEY_3 => Some('#'),
            K::KEY_4 => Some('$'),
            K::KEY_5 => Some('%'),
            K::KEY_6 => Some('^'),
            K::KEY_7 => Some('&'),
            K::KEY_8 => Some('*'),
            K::KEY_9 => Some('('),
            K::KEY_0 => Some(')'),
            K::KEY_SEMICOLON => Some(':'),
            K::KEY_APOSTROPHE => Some('"'),
            K::KEY_COMMA => Some('<'),
            K::KEY_DOT => Some('>'),
            K::KEY_LEFTBRACE => Some('{'),
            K::KEY_RIGHTBRACE => Some('}'),
            K::KEY_GRAVE => Some('~'),
            K::KEY_SLASH => Some('?'),
            K::KEY_BACKSLASH => Some('|'),
            K::KEY_MINUS => Some('_'),
            K::KEY_EQUAL => Some('+'),
            K::KEY_SPACE => Some(' '),
            _ => None,
        };
    }

    match key {
        K::KEY_A => Some('a'),
        K::KEY_B => Some('b'),
        K::KEY_C => Some('c'),
        K::KEY_D => Some('d'),
        K::KEY_E => Some('e'),
        K::KEY_F => Some('f'),
        K::KEY_G => Some('g'),
        K::KEY_H => Some('h'),
        K::KEY_I => Some('i'),
        K::KEY_J => Some('j'),
        K::KEY_K => Some('k'),
        K::KEY_L => Some('l'),
        K::KEY_M => Some('m'),
        K::KEY_N => Some('n'),
        K::KEY_O => Some('o'),
        K::KEY_P => Some('p'),
        K::KEY_Q => Some('q'),
        K::KEY_R => Some('r'),
        K::KEY_S => Some('s'),
        K::KEY_T => Some('t'),
        K::KEY_U => Some('u'),
        K::KEY_V => Some('v'),
        K::KEY_W => Some('w'),
        K::KEY_X => Some('x'),
        K::KEY_Y => Some('y'),
        K::KEY_Z => Some('z'),
        K::KEY_1 => Some('1'),
        K::KEY_2 => Some('2'),
        K::KEY_3 => Some('3'),
        K::KEY_4 => Some('4'),
        K::KEY_5 => Some('5'),
        K::KEY_6 => Some('6'),
        K::KEY_7 => Some('7'),
        K::KEY_8 => Some('8'),
        K::KEY_9 => Some('9'),
        K::KEY_0 => Some('0'),
        K::KEY_SEMICOLON => Some(';'),
        K::KEY_APOSTROPHE => Some('\''),
        K::KEY_COMMA => Some(','),
        K::KEY_DOT => Some('.'),
        K::KEY_LEFTBRACE => Some('['),
        K::KEY_RIGHTBRACE => Some(']'),
        K::KEY_GRAVE => Some('`'),
        K::KEY_SLASH => Some('/'),
        K::KEY_BACKSLASH => Some('\\'),
        K::KEY_MINUS => Some('-'),
        K::KEY_EQUAL => Some('='),
        K::KEY_SPACE => Some(' '),
        _ => None,
    }
}
