use crate::keyboard::KeyEvent;
use evdev::KeyCode;

pub(super) fn char_to_us_key_event(ch: char) -> Option<KeyEvent> {
    use KeyCode as K;
    let (key, shift) = match ch {
        'a' | 'A' => (K::KEY_A, ch.is_uppercase()),
        'b' | 'B' => (K::KEY_B, ch.is_uppercase()),
        'c' | 'C' => (K::KEY_C, ch.is_uppercase()),
        'd' | 'D' => (K::KEY_D, ch.is_uppercase()),
        'e' | 'E' => (K::KEY_E, ch.is_uppercase()),
        'f' | 'F' => (K::KEY_F, ch.is_uppercase()),
        'g' | 'G' => (K::KEY_G, ch.is_uppercase()),
        'h' | 'H' => (K::KEY_H, ch.is_uppercase()),
        'i' | 'I' => (K::KEY_I, ch.is_uppercase()),
        'j' | 'J' => (K::KEY_J, ch.is_uppercase()),
        'k' | 'K' => (K::KEY_K, ch.is_uppercase()),
        'l' | 'L' => (K::KEY_L, ch.is_uppercase()),
        'm' | 'M' => (K::KEY_M, ch.is_uppercase()),
        'n' | 'N' => (K::KEY_N, ch.is_uppercase()),
        'o' | 'O' => (K::KEY_O, ch.is_uppercase()),
        'p' | 'P' => (K::KEY_P, ch.is_uppercase()),
        'q' | 'Q' => (K::KEY_Q, ch.is_uppercase()),
        'r' | 'R' => (K::KEY_R, ch.is_uppercase()),
        's' | 'S' => (K::KEY_S, ch.is_uppercase()),
        't' | 'T' => (K::KEY_T, ch.is_uppercase()),
        'u' | 'U' => (K::KEY_U, ch.is_uppercase()),
        'v' | 'V' => (K::KEY_V, ch.is_uppercase()),
        'w' | 'W' => (K::KEY_W, ch.is_uppercase()),
        'x' | 'X' => (K::KEY_X, ch.is_uppercase()),
        'y' | 'Y' => (K::KEY_Y, ch.is_uppercase()),
        'z' | 'Z' => (K::KEY_Z, ch.is_uppercase()),
        '1' => (K::KEY_1, false),
        '2' => (K::KEY_2, false),
        '3' => (K::KEY_3, false),
        '4' => (K::KEY_4, false),
        '5' => (K::KEY_5, false),
        '6' => (K::KEY_6, false),
        '7' => (K::KEY_7, false),
        '8' => (K::KEY_8, false),
        '9' => (K::KEY_9, false),
        '0' => (K::KEY_0, false),
        '!' => (K::KEY_1, true),
        '@' => (K::KEY_2, true),
        '#' => (K::KEY_3, true),
        '$' => (K::KEY_4, true),
        '%' => (K::KEY_5, true),
        '^' => (K::KEY_6, true),
        '&' => (K::KEY_7, true),
        '*' => (K::KEY_8, true),
        '(' => (K::KEY_9, true),
        ')' => (K::KEY_0, true),
        ';' => (K::KEY_SEMICOLON, false),
        ':' => (K::KEY_SEMICOLON, true),
        '\'' => (K::KEY_APOSTROPHE, false),
        '"' => (K::KEY_APOSTROPHE, true),
        ',' => (K::KEY_COMMA, false),
        '<' => (K::KEY_COMMA, true),
        '.' => (K::KEY_DOT, false),
        '>' => (K::KEY_DOT, true),
        '[' => (K::KEY_LEFTBRACE, false),
        '{' => (K::KEY_LEFTBRACE, true),
        ']' => (K::KEY_RIGHTBRACE, false),
        '}' => (K::KEY_RIGHTBRACE, true),
        '`' => (K::KEY_GRAVE, false),
        '~' => (K::KEY_GRAVE, true),
        '/' => (K::KEY_SLASH, false),
        '?' => (K::KEY_SLASH, true),
        '\\' => (K::KEY_BACKSLASH, false),
        '|' => (K::KEY_BACKSLASH, true),
        '-' => (K::KEY_MINUS, false),
        '_' => (K::KEY_MINUS, true),
        '=' => (K::KEY_EQUAL, false),
        '+' => (K::KEY_EQUAL, true),
        ' ' => (K::KEY_SPACE, false),
        _ => return None,
    };

    Some(KeyEvent {
        keycode: key.code(),
        shift,
        layout_is_ru: false,
    })
}
