use crate::typing_candidate::TypingCandidateFamily;

use super::builders::{layout_only_rule, policy_rule, rule, safety_rule, weighted_rule};
use super::ids;
use super::rules;
use super::types::{TypingRuleDefinition, TypingRuleRequiredSafety, TypingRuleSafety};
use super::weights::default_typing_rule_family_weight;

pub(super) static RULES: &[TypingRuleDefinition] = &[
    weighted_rule(
        ids::MOVED_PREFIX_PAIR,
        Some(10),
        TypingCandidateFamily::Structural,
        98.0,
        TypingRuleSafety::Always,
        rules::apply_moved_prefix_pair,
    ),
    rule(
        ids::SPLIT_WORD_PAIR,
        20,
        TypingCandidateFamily::Structural,
        rules::apply_split_word_pair,
    ),
    rule(
        ids::VISUAL_B,
        30,
        TypingCandidateFamily::Visual,
        rules::apply_visual_b,
    ),
    rule(
        ids::PERSONAL_PHRASE,
        40,
        TypingCandidateFamily::Exact,
        rules::apply_personal_phrase,
    ),
    rule(
        ids::PERSONAL_TOKEN,
        50,
        TypingCandidateFamily::Exact,
        rules::apply_personal_token,
    ),
    layout_only_rule(
        ids::DUPLICATE_LAYOUT_PREFIX,
        60,
        TypingRuleSafety::Always,
        TypingRuleRequiredSafety::Strict,
        rules::apply_duplicate_layout_prefix,
    ),
    layout_only_rule(
        ids::MIXED_SCRIPT_LAYOUT,
        70,
        TypingRuleSafety::Always,
        TypingRuleRequiredSafety::Strict,
        rules::apply_mixed_script_layout,
    ),
    layout_only_rule(
        ids::LAYOUT_TECHNICAL,
        80,
        TypingRuleSafety::Always,
        TypingRuleRequiredSafety::Strict,
        rules::apply_layout_technical,
    ),
    layout_only_rule(
        ids::LAYOUT_RU_TO_EN,
        90,
        TypingRuleSafety::PlainLayoutAutocorrect,
        TypingRuleRequiredSafety::Strict,
        rules::apply_layout_ru_to_en,
    ),
    layout_only_rule(
        ids::LAYOUT_EN_TO_RU,
        100,
        TypingRuleSafety::PlainLayoutAutocorrect,
        TypingRuleRequiredSafety::Experimental,
        rules::apply_layout_en_to_ru,
    ),
    policy_rule(
        ids::CONTEXTUAL_LAYOUT_EN_TO_RU,
        None,
        TypingCandidateFamily::Layout,
        default_typing_rule_family_weight(TypingCandidateFamily::Layout),
        TypingRuleSafety::ContextualLayoutAutocorrect,
        false,
        TypingRuleRequiredSafety::Strict,
        rules::apply_layout_en_to_ru,
    ),
    rule(
        ids::CYRILLIC_CASE,
        110,
        TypingCandidateFamily::Typo,
        rules::apply_cyrillic_case,
    ),
    rule(
        ids::HARD_SIGN,
        120,
        TypingCandidateFamily::Typo,
        rules::apply_hard_sign,
    ),
    rule(
        ids::ADJACENT_TRANSPOSITION,
        130,
        TypingCandidateFamily::Typo,
        rules::apply_adjacent_transposition,
    ),
    safety_rule(
        ids::REPEATED_LETTER,
        140,
        TypingCandidateFamily::Typo,
        TypingRuleRequiredSafety::Normal,
        rules::apply_repeated_letter,
    ),
    safety_rule(
        ids::SINGLE_LETTER_SUBSTITUTION,
        150,
        TypingCandidateFamily::Typo,
        TypingRuleRequiredSafety::Experimental,
        rules::apply_single_letter_substitution,
    ),
    policy_rule(
        ids::VERB_ENDING,
        Some(160),
        TypingCandidateFamily::Typo,
        92.0,
        TypingRuleSafety::Always,
        false,
        TypingRuleRequiredSafety::Experimental,
        rules::apply_verb_ending,
    ),
    safety_rule(
        ids::VOWEL_CONFUSION,
        170,
        TypingCandidateFamily::Typo,
        TypingRuleRequiredSafety::Experimental,
        rules::apply_vowel_confusion,
    ),
    safety_rule(
        ids::EXTRA_LETTERS,
        180,
        TypingCandidateFamily::Typo,
        TypingRuleRequiredSafety::Experimental,
        rules::apply_extra_letters,
    ),
    safety_rule(
        ids::MISSING_LETTER,
        190,
        TypingCandidateFamily::Typo,
        TypingRuleRequiredSafety::Normal,
        rules::apply_missing_letter,
    ),
    safety_rule(
        ids::GLUED_PHRASE,
        200,
        TypingCandidateFamily::Structural,
        TypingRuleRequiredSafety::Normal,
        rules::apply_glued_phrase,
    ),
];
