use crate::typing_candidate::TypingCandidateFamily;

use super::builders::{
    contextual_layout_rule, experimental_weighted_rule, layout_only_rule, rule, safety_rule,
    weighted_rule,
};
use super::ids;
use super::priorities;
use super::rules;
use super::types::{TypingRuleDefinition, TypingRuleRequiredSafety, TypingRuleSafety};

pub(super) static RULES: &[TypingRuleDefinition] = &[
    weighted_rule(
        ids::MOVED_PREFIX_PAIR,
        Some(priorities::MOVED_PREFIX_PAIR),
        TypingCandidateFamily::Structural,
        priorities::MOVED_PREFIX_PAIR_WEIGHT,
        TypingRuleSafety::Always,
        rules::apply_moved_prefix_pair,
    ),
    rule(
        ids::SPLIT_WORD_PAIR,
        priorities::SPLIT_WORD_PAIR,
        TypingCandidateFamily::Structural,
        rules::apply_split_word_pair,
    ),
    rule(
        ids::VISUAL_B,
        priorities::VISUAL_B,
        TypingCandidateFamily::Visual,
        rules::apply_visual_b,
    ),
    rule(
        ids::PERSONAL_PHRASE,
        priorities::PERSONAL_PHRASE,
        TypingCandidateFamily::Exact,
        rules::apply_personal_phrase,
    ),
    rule(
        ids::PERSONAL_TOKEN,
        priorities::PERSONAL_TOKEN,
        TypingCandidateFamily::Exact,
        rules::apply_personal_token,
    ),
    layout_only_rule(
        ids::DUPLICATE_LAYOUT_PREFIX,
        priorities::DUPLICATE_LAYOUT_PREFIX,
        TypingRuleSafety::Always,
        TypingRuleRequiredSafety::Strict,
        rules::apply_duplicate_layout_prefix,
    ),
    layout_only_rule(
        ids::MIXED_SCRIPT_LAYOUT,
        priorities::MIXED_SCRIPT_LAYOUT,
        TypingRuleSafety::Always,
        TypingRuleRequiredSafety::Strict,
        rules::apply_mixed_script_layout,
    ),
    layout_only_rule(
        ids::LAYOUT_TECHNICAL,
        priorities::LAYOUT_TECHNICAL,
        TypingRuleSafety::Always,
        TypingRuleRequiredSafety::Strict,
        rules::apply_layout_technical,
    ),
    layout_only_rule(
        ids::LAYOUT_RU_TO_EN,
        priorities::LAYOUT_RU_TO_EN,
        TypingRuleSafety::PlainLayoutAutocorrect,
        TypingRuleRequiredSafety::Strict,
        rules::apply_layout_ru_to_en,
    ),
    layout_only_rule(
        ids::LAYOUT_EN_TO_RU,
        priorities::LAYOUT_EN_TO_RU,
        TypingRuleSafety::PlainLayoutAutocorrect,
        TypingRuleRequiredSafety::Experimental,
        rules::apply_layout_en_to_ru,
    ),
    contextual_layout_rule(
        ids::CONTEXTUAL_LAYOUT_EN_TO_RU,
        rules::apply_layout_en_to_ru,
    ),
    contextual_layout_rule(
        ids::EXPERIMENTAL_LAYOUT_EN_TO_RU,
        rules::apply_layout_en_to_ru,
    ),
    rule(
        ids::CYRILLIC_CASE,
        priorities::CYRILLIC_CASE,
        TypingCandidateFamily::Typo,
        rules::apply_cyrillic_case,
    ),
    rule(
        ids::HARD_SIGN,
        priorities::HARD_SIGN,
        TypingCandidateFamily::Typo,
        rules::apply_hard_sign,
    ),
    rule(
        ids::ADJACENT_TRANSPOSITION,
        priorities::ADJACENT_TRANSPOSITION,
        TypingCandidateFamily::Typo,
        rules::apply_adjacent_transposition,
    ),
    safety_rule(
        ids::REPEATED_LETTER,
        priorities::REPEATED_LETTER,
        TypingCandidateFamily::Typo,
        TypingRuleRequiredSafety::Normal,
        rules::apply_repeated_letter,
    ),
    safety_rule(
        ids::SINGLE_LETTER_SUBSTITUTION,
        priorities::SINGLE_LETTER_SUBSTITUTION,
        TypingCandidateFamily::Typo,
        TypingRuleRequiredSafety::Experimental,
        rules::apply_single_letter_substitution,
    ),
    experimental_weighted_rule(
        ids::VERB_ENDING,
        priorities::VERB_ENDING,
        TypingCandidateFamily::Typo,
        priorities::VERB_ENDING_WEIGHT,
        rules::apply_verb_ending,
    ),
    safety_rule(
        ids::VOWEL_CONFUSION,
        priorities::VOWEL_CONFUSION,
        TypingCandidateFamily::Typo,
        TypingRuleRequiredSafety::Experimental,
        rules::apply_vowel_confusion,
    ),
    safety_rule(
        ids::EXTRA_LETTERS,
        priorities::EXTRA_LETTERS,
        TypingCandidateFamily::Typo,
        TypingRuleRequiredSafety::Experimental,
        rules::apply_extra_letters,
    ),
    safety_rule(
        ids::MISSING_LETTER,
        priorities::MISSING_LETTER,
        TypingCandidateFamily::Typo,
        TypingRuleRequiredSafety::Normal,
        rules::apply_missing_letter,
    ),
    safety_rule(
        ids::GLUED_PHRASE,
        priorities::GLUED_PHRASE,
        TypingCandidateFamily::Structural,
        TypingRuleRequiredSafety::Normal,
        rules::apply_glued_phrase,
    ),
];
